#!/usr/bin/env python3
"""Generate the Port Grid Generator demo dashboard (#267).

Shows exactly what the editor's **Generate Port Grid** action produces: a
24-port switch faceplate laid out by the generator (odd/even two-row ordering
with faceplate block gaps) and colored live by the standard status coloring
(green = up, red = down). Each port binds to the exporter's wm_port_status
series, so ports 7 & 19 read down (red), port 13 flaps, and the rest are up.

The node math here mirrors src/gridGenerator.ts::generatePortGrid so the demo
stays faithful to the real feature. Run from testing/:
    python3 scripts/generate-port-grid-demo.py
"""
import copy
import json

# --- generator parameters (the "24-port switch" preset) ---------------------
COUNT = 24
ORDERING = "odd-even"
H_SPACING = 46
V_SPACING = 34
GROUP_SIZE = 6      # faceplate blocks of 12 ports (6 columns)
GROUP_GAP = 18
NODE_SIZE = 4       # padding
ORIGIN_X = 170
ORIGIN_Y = 210
LABEL_PATTERN = "Gi1/0/{n}"
STATUS_TEMPLATE = "PORT Gi1/0/{n}"   # matches the wm_port_status legend "PORT {{port}}"
UP_COLOR = "#73BF69"
DOWN_COLOR = "#F2495C"


def cell(i):
    # odd-even: odd ports (i even) on the top row, even ports below.
    return i % 2, i // 2


base = json.load(open("grafana/dashboards/wm-rack-ports.json"))
d = copy.deepcopy(base)
d["uid"] = "wm-port-grid"
d["title"] = "WAN Demo — Switch Port Board (generated)"
d["description"] = (
    "A 24-port switch faceplate produced by the Generate Port Grid action: "
    "odd/even faceplate ordering with block gaps, colored live by status "
    "coloring (green up / red down) from wm_port_status (#267)."
)
d["version"] = 0

panel = [p for p in d["panels"] if p.get("type", "").startswith("tamir")][0]
panel["title"] = "Switch Port Board — generated by Generate Port Grid"
wm = panel["options"]["weathermap"]

# Template node = one of the existing rack port nodes (keeps every required
# field: anchors, colors, nodeIcon, etc.).
template = copy.deepcopy(wm["nodes"][0])

nodes = []
for i in range(COUNT):
    port = i + 1
    row, col = cell(i)
    x = ORIGIN_X + col * H_SPACING + (col // GROUP_SIZE) * GROUP_GAP
    y = ORIGIN_Y + row * V_SPACING
    node = copy.deepcopy(template)
    node["id"] = f"port-{port}"
    node["position"] = [x, y]
    node["label"] = LABEL_PATTERN.format(n=port)
    node["showLabel"] = True
    node["padding"] = {"horizontal": NODE_SIZE, "vertical": NODE_SIZE}
    node["statusQuery"] = STATUS_TEMPLATE.format(n=port)
    # Exactly what "Status coloring" stamps: green up (>=1), red down (0).
    node["statusValueMappings"] = [
        {"value": 0, "color": DOWN_COLOR},
        {"value": 1, "color": UP_COLOR},
    ]
    node["nodeStatusColorTarget"] = "background"
    nodes.append(node)

wm["nodes"] = nodes
wm["links"] = []  # a port board has no links
wm["scale"] = []  # no links → the traffic color scale legend is just noise
wm["settings"]["scale"]["title"] = ""  # drop the leftover scale title too

# A generated board stands on its own — drop the faceplate background image so
# the demo shows the pure generator output.
wm["settings"]["panel"].pop("backgroundImage", None)

with open("grafana/dashboards/wm-port-grid.json", "w") as f:
    json.dump(d, f, indent=2)
print(f"wrote wm-port-grid.json — {len(nodes)} generated port nodes")
