#!/usr/bin/env python3
"""Generate the Rack Elevation demo dashboard (#319).

Shows what the editor's **Generate Rack Elevation** action produces: a rack of
*different* devices placed by rack-unit (U), where each device with ports also
gets its port faceplate drawn (via the #267 port-grid engine). Every node is
colored live from wm_port_status (green up / red down): R-SW1 port 5 is down,
SRV-2's standby NIC is down, SRV-3's iLO is down.

The math here mirrors src/rackGenerator.ts + src/gridGenerator.ts so the demo
stays faithful to the real feature. Run from testing/:
    python3 scripts/generate-rack-elevation-demo.py
"""
import copy
import json
import math

UP, DOWN = "#73BF69", "#F2495C"


def r(x):
    """Round half up, matching JS Math.round (src/rackGenerator.ts)."""
    return math.floor(x + 0.5)


# --- rack + device layout (matches the editor's defaults/shape) -------------
RACK_UNITS = 12
U_PX = 40
LABEL_WIDTH = 90
PORT_H, PORT_V = 34, 28
ORIGIN_X, ORIGIN_Y = 150, 110
# Chassis geometry — mirrors the hybrid rack in src/rackGenerator.ts (#321).
RAIL_W, RAIL_GAP = 18, 5

# label, U (start), height, port count, port label pattern, status query template
DEVICES = [
    ("R-SW1", 10, 2, 8, "Gi0/{n}", "PORT R-SW1 Gi0/{n}"),
    ("R-SW2", 8, 2, 8, "Gi0/{n}", "PORT R-SW2 Gi0/{n}"),
    ("R-RTR", 6, 1, 4, "Ge0/{n}", "PORT R-RTR Ge0/{n}"),
    ("R-FW", 5, 1, 4, "P{n}", "PORT R-FW P{n}"),
    ("SRV-1", 3, 1, 0, "", "PORT SRV-1 eth0"),
    ("SRV-2", 2, 1, 0, "", "PORT SRV-2 eth1"),   # SRV-2 standby NIC is down
    ("SRV-3", 1, 1, 0, "", "PORT SRV-3 ilo"),    # SRV-3 iLO is down
]

base = json.load(open("grafana/dashboards/wm-rack-cabling.json"))
d = copy.deepcopy(base)
d["uid"] = "wm-rack-elevation"
d["title"] = "WAN Demo — Rack Elevation (generated)"
d["description"] = (
    "A rack of different devices laid out by rack unit by the Generate Rack "
    "Elevation action (#319): switches carry their port faceplates (via the "
    "#267 engine), colored live green up / red down from wm_port_status."
)
d["version"] = 0

panel = [p for p in d["panels"] if p.get("type", "").startswith("tamir")][0]
panel["title"] = "Rack Elevation — generated by Generate Rack Elevation"
wm = panel["options"]["weathermap"]
template = copy.deepcopy(wm["nodes"][0])


_uid = 0


def mk(label, pos, status_query=None):
    global _uid
    _uid += 1
    n = copy.deepcopy(template)
    n["id"] = f"rack-{_uid}"
    n["position"] = [pos[0], pos[1]]
    n["label"] = label
    n["showLabel"] = True
    n["nodeIcon"] = {"src": "", "name": "", "size": {"width": 0, "height": 0},
                     "padding": {"vertical": 0, "horizontal": 0}, "drawInside": False}
    if status_query:
        n["statusQuery"] = status_query
        n["statusValueMappings"] = [{"value": 0, "color": DOWN}, {"value": 1, "color": UP}]
        n["nodeStatusColorTarget"] = "background"
    else:
        n.pop("statusQuery", None)
        n.pop("statusValueMappings", None)
    return n


def transparent(n):
    n["colors"] = {**n["colors"], "background": "transparent", "border": "transparent"}
    return n


# Hybrid rack chassis (#321): uniform full-width bars between two mounting rails,
# device names as their own nodes, U-numbers on the left rail, and the labeled
# port faceplates to the right of the rack frame.
BODY_CX = ORIGIN_X + LABEL_WIDTH / 2
FACE_X = ORIGIN_X + LABEL_WIDTH + RAIL_GAP + RAIL_W + 46

nodes = []
for label, u, height, pcount, plabel, ptmpl in DEVICES:
    top_u = u + height - 1
    top_y = ORIGIN_Y + (RACK_UNITS - top_u) * U_PX  # bottom-up
    center_y = top_y + (height * U_PX) / 2

    # Uniform full-width bar: empty (hidden-label) node, width = 2×padding. A
    # port-bearing bar stays a neutral chassis face; a device-status bar colors.
    bar = mk("", [BODY_CX, center_y], status_query=None if pcount > 0 else ptmpl)
    bar["showLabel"] = False
    bar["padding"] = {"horizontal": r(LABEL_WIDTH / 2), "vertical": max(4, r(height * U_PX / 2) - 2)}
    nodes.append(bar)

    # Device name rides on top of the bar as its own transparent node.
    name = transparent(mk(label, [BODY_CX, center_y]))
    name["padding"] = {"horizontal": 2, "vertical": 2}
    name["fontBold"] = True
    name["zIndex"] = 1
    nodes.append(name)

    if pcount > 0:
        rows = 2 if pcount > 12 else 1
        cols = math.ceil(pcount / rows)
        py0 = center_y - ((rows - 1) * PORT_V) / 2
        for i in range(pcount):
            port = i + 1
            row, col = i // cols, i % cols
            x = FACE_X + col * PORT_H
            y = py0 + row * PORT_V
            lbl = plabel.format(n=port)
            p = mk(lbl, [x, y], status_query=ptmpl.format(n=port))
            p["padding"] = {"horizontal": 2, "vertical": 2}
            nodes.append(p)

# U-position markers on the left rail.
MARKER_X = ORIGIN_X - RAIL_GAP - RAIL_W / 2
for uu in range(1, RACK_UNITS + 1):
    cy = ORIGIN_Y + (RACK_UNITS - uu) * U_PX + U_PX / 2
    m = transparent(mk(f"U{uu}", [MARKER_X, cy]))
    m["padding"] = {"horizontal": 2, "vertical": 1}
    m["fontSize"] = 9
    m["zIndex"] = 1
    nodes.append(m)

# Chassis: outer frame + two mounting rails, behind the equipment.
RACK_CY = ORIGIN_Y + (RACK_UNITS * U_PX) / 2
RACK_HALF_H = r(RACK_UNITS * U_PX / 2)


def rail(cx):
    n = mk("", [cx, RACK_CY])
    n["showLabel"] = False
    n["padding"] = {"horizontal": r(RAIL_W / 2), "vertical": RACK_HALF_H}
    n["colors"] = {**n["colors"], "background": "transparent"}
    n["zIndex"] = -1
    return n


left_rail = rail(ORIGIN_X - RAIL_GAP - RAIL_W / 2)
right_rail = rail(ORIGIN_X + LABEL_WIDTH + RAIL_GAP + RAIL_W / 2)
frame_left = ORIGIN_X - RAIL_GAP - RAIL_W - 6
frame_right = ORIGIN_X + LABEL_WIDTH + RAIL_GAP + RAIL_W + 6
frame_cx = (frame_left + frame_right) / 2
frame = mk("", [frame_cx, RACK_CY])
frame["showLabel"] = False
frame["padding"] = {"horizontal": r((frame_right - frame_left) / 2), "vertical": RACK_HALF_H + 5}
frame["colors"] = {**frame["colors"], "background": "transparent"}
frame["zIndex"] = -2

# Frame furthest back, then the two rails, then the equipment (matches the
# generator's unshift order).
nodes = [frame, left_rail, right_rail] + nodes

wm["nodes"] = nodes
wm["links"] = []
wm["scale"] = []
wm["settings"]["scale"]["title"] = ""
wm["settings"]["panel"].pop("backgroundImage", None)

with open("grafana/dashboards/wm-rack-elevation.json", "w") as f:
    json.dump(d, f, indent=2)
print(f"wrote wm-rack-elevation.json — {len(nodes)} nodes ({len(DEVICES)} devices)")
