apiVersion: 1
datasources:
  - name: MySQL
    uid: mysql-wm
    type: mysql
    access: proxy
    url: mysql-wm:3306
    user: wm
    jsonData:
      database: wm
    secureJsonData:
      password: wm
